site_name: Engineer's Handbook
site_url: https://docs.devopslearning.ru
site_author: Andrey Deryugin
site_description: >-
  Моя библиотека знаний.


# Repository
repo_name: andrey97d/andrey97d.github.io
repo_url: https://github.com/andrey97d/andrey97d.github.io

  
copyright: Copyright &copy; 2026 Andrey Deryugin

theme:
  name: material
  logo: assets/images/connection.png
  language: ru
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.path
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - search.suggest
    - search.highlight
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

    
extra:
  generator: false


nav:
  - Главная: index.md
  - How-to:
    - Обзор: how-to/index.md
    - Настраиваем Nginx: how-to/nginx.md
    - Создаем свою страницу: how-to/create-website.md
  - DevOps Core:
    - Linux :
      - Обзор: devops-core/linux/index.md
    - Git:
      - Шпаргалка: devops-core/git/cheatsheet.md
      - Workflow: devops-core/git/workflow.md
      - Ветки: devops-core/git/branches.md
      - Изменения: devops-core/git/changes.md
      - Синхронизация: devops-core/git/sync.md
      - История и откаты: devops-core/git/history.md
      - Продвинутое: devops-core/git/advanced.md
      - Хаки: devops-core/git/life-hack.md
    - Docker:
      - Обзор: devops-core/docker/index.md
      - Dockerfile: devops-core/docker/dockerfile.md
      - Сети: devops-core/docker/network.md
      - Volume: devops-core/docker/volume.md
      - Compose: devops-core/docker/compose.md
  - Infrastructure:
    - Kubernetes:
      - Обзор: infra/kubernetes/index.md
    - CI/CD: 
      - Обзор: infra/cicd/index.md
    - Terraform:
      - Обзор: infra/terra/index.md
    - Nginx:
      - Обзор: infra/nginx/index.md
  - Programming:
    - Python:
      - Тест: programming/python/index.md
  - Data:
    - Базы данных:
      - Обзор: data/database/index.md
    - Excel:
      - Шпаргалка: data/excel/cheatsheet.md
  - Other:
    - Redfish / BMC:
      - Обзор: other/redfish/index.md


  
    
