site_name: My Docs
site_url: https://docs.devopslearning.ru


theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy


nav:
  - Главная: index.md
  - Docker:
    - Обзор: docker/index.md
    - Сети: docker/network.md
  - Linux:
    - Обзор: linux/index.md
  - Git:
    - Обзор: git/index.md
  - Kubernetes:
    - Обзор: kubernetes/index.md
  - Redfish / BMC:
    - Обзор: redfish/index.md
  - Шпаргалки:
    - Обзор: cheatsheets/index.md
    